"""rate_limit_hits table

Revision ID: 7dc09e8ab04f
Revises: b851ccee297f
Create Date: 2026-06-12 01:21:48.946371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc09e8ab04f'
down_revision = 'b851ccee297f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rkey', sa.String(length=120), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit_hits')
    # ### end Alembic commands ###
